title:              Brett Neubeck
email:              Brett.Neubeck@gmail.com
description:        Data Science Project Portfolio
author:             Brett Neubeck
baseurl:            #"/startbootstrap-clean-blog-jekyll"
url:                "https://brettneubeck.github.io"

# Social Profiles
twitter_username:   #SBootstrap
github_username:    brettneubeck
facebook_username:  #StartBootstrap
instagram_username:  
linkedin_username: brett-neubeck-aa81106

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
